services:
  - type: web
    name: api-java-spring-boot
    runtime: docker
    plan: free
    healthCheckPath: /clientes
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: clientes-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: clientes-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: clientes-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: clientes-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: clientes-db
          property: password

databases:
  - name: clientes-db
    plan: free
    databaseName: clientes_db
